apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-secrets
type: Opaque
data:
# Base64 String: kevin@google.com
  PG_USER_EMAIL: a2V2aW5AZ29vZ2xlLmNvbQ==
# Base64 String: passwordSecreto
  PG_USER_PASSWORD: cGFzc3dvcmRTZWNyZXRv